# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-06 09:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_sample'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sample',
            new_name='Samples',
        ),
    ]
